AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - spec/**/*
    - node_modules/**/*
    - Gemfile
    - Rakefile
    - config.ru
    - gems/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
