AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - spec/**/*
    - node_modules/**/*
    - Gemfile
    - Rakefile
    - config.ru

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30