version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    env_file: .env
    volumes:
      - .:/cheezecake_blog
      - static_files:/cheezecake_blog/public
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

  postgres:
    image: postgres:10.6
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

volumes:
  static_files: