version: "3"
services:
  nginx:
    image: nginx
    links:
      - web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
