version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    image: cheezecake:1
#    container_name: cheezecake_web
    env_file: .env
    volumes:
      - .:/cheezecake_blog
    ports:
      - 3030:3000
    stdin_open: true
    tty: true

  client:
    build:
      context: .
      dockerfile: ./docker/web_client/Dockerfile
    command: tail -f /dev/null
    volumes:
      - ./web_client:/root/webapp
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

  postgres:
    image: postgres:10.6
#    container_name: cheezecake_postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
