version: "3"
services:
  web:
    volumes:
      - .:/cheezecake_blog
      - static_files:/cheezecake_blog/public

  nginx:
    image: nginx
    container_name: cheezecake_nginx
    links:
      - web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_files:/cheezecake_blog/public
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443

volumes:
  static_files:
