version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node-browsers
        environment:
          RAILS_ENV: test
          DATABASE_HOST: localhost
      - image: circleci/postgres:10.6
    steps:
      - checkout
      - run:
          name: Copy config
          command: |
            cp ./config/database.yml.example ./config/database.yml
            cp ./config/master.key.example ./config/master.key

      - restore_cache:
          name: Restore bundle cache
          keys:
            - cheezecake-is-good-v2-{{ checksum "Gemfile.lock" }} # to clear the cache, upgrade the version

      - run:
          name: Bundle install
          command: bundle check || bundle install # default path is vendor/bundle

      - save_cache:
          name: Save bundle cache
          key: cheezecake-is-good-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          name: Restore yarn cache
          keys:
            - cheezecake-is-good-v3-{{ checksum "./web_client/yarn.lock" }} # to clear the cache, upgrade the version

      - run:
          name: Yarn install
          working_directory: ./web_client
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          name: Save yarn cache
          key: cheezecake-is-good-v3-{{ checksum "./web_client/yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Wait for Database
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: |
            bin/rails db:create db:migrate

      - run:
          name: Rubocop
          command: |
            bundle exec rubocop -c .rubocop.yml

      - run:
          name: ESlint
          command: |
            ./web_client/node_modules/.bin/eslint "web_client/**"

      - run:
          name: Rspec
          command: |
            bundle exec rspec