# These config values will be shared by all environments but can be overridden.
common: &common
  client_id: "ruby-kafka"

development:
  <<: *common
  brokers:
    - kafka:19092

test:
  <<: *common
  brokers:
    - kafka:9092

production:
  <<: *common
  brokers:
    - kafka:9092
#    - kafka1.myapp.com:9092
#    - kafka2.myapp.com:9092
#    - kafka3.myapp.com:9092
